praktikum/urls.py
from django.conf.urls import include, url
from django.urls import re_path
from django.contrib import admin
import webapp.urls as webapp
from webapp import views


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    url(r'^webapp/', include(('webapp.urls', 'webapp'), namespace='webapp')),
]

webapp/urls.py
from django.urls import path
from django.conf.urls import include, url
from .views import home
from .views import skills
from .views import portfolio
from .views import tips
from .views import form
from .views import myschedule
from .views import delete_all


urlpatterns = [
	url(r'^home/', home, name='home'),
	url(r'^skills/', skills, name='skills'),
	url(r'^portfolio/', portfolio, name='portfolio'),
	url(r'^tips/', tips, name='tips'),
	url(r'^form/', form, name='form'),
    path('activity/', myschedule, name='activity'),
    url(r'^activity/delete', delete_all, name='deleteall')


] 

webapp/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.

class Schedule(models.Model):
	kegiatan = models.CharField(max_length=50)
	location = models.CharField(max_length=50)
	category = models.CharField(max_length=50)
	tanggal = models.DateField(default=timezone.now)
	waktu = models.TimeField(default=timezone.now)

webapp/forms.py
from django import forms
from .models import Schedule
from django.forms import  ModelForm

class Message_Form(ModelForm):
	class Meta:
		model = Schedule
		fields = ['kegiatan','location','category','tanggal','waktu']

webapp/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect

from .models import Schedule
from .forms import Message_Form

# Create your views here.
def home(request):
	return render(request, 'home.html')
	
def skills(request):
	return render(request, 'skills.html')
	
def portfolio(request):
	return render(request, 'portfolio.html')
	
def tips(request):
	return render(request, 'tips.html')

def form(request):
	return render(request, 'form.html')



def myschedule(request):
	events = Schedule.objects.all().values()

	if request.method == "POST":
		form = Message_Form(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('webapp:activity'))
	else:
		form = Message_Form()

	response = {'abang': form, 'events': events}
	html = 'page5.html'
	return render(request, html, response)

def delete_all(request):
	Schedule.objects.all().delete()
	return HttpResponseRedirect(reverse('webapp:activity'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}

templates/to_do_list.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hai semua, berikut adalah Catatan Harianku</h3>
<br><br>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <table align="center" style="text-align: center">
            <tr>
                <th>Tanggal</th>
                <th>Yang akan dikerjakan</th>
            </tr>
            {% for diary_data in diary_dict %}
                <tr>
                    <td class="date">{{ diary_data.date }}</td>
                    <td class="activity">{{ diary_data.activity }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-md-6 col-xs-6">
        <form method="POST" action="add_activity/">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        Tanggal
                    </td>
                    <td>
                        <input type="datetime-local" name="date" id="date" required="required"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        Kegiatan
                    </td>
                    <td>
                        <input type="text" name="activity" id="activity" size="25"/>
                    </td>
                </tr>
            </table>
            <button type="submit" class="button btn-success">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

webapp/templates/form.html
{% load staticfiles %}
{%load static%}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet'>
    <link href="{%static 'css/style.css'%}" rel="stylesheet" type="text/css">
<!--<html lang="en">-->


    <title>Register</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<header>
  {% include "partials/header.html" %}
</header>

<body>


<div class="container" style="max-width: 500px">
  <h2 style="text-align: center; font-family: 'Montserrat'; font-size: 36px">Register Account</h2>
  <form>
    <div class="form-group">
      <label for="name">Name:</label>
      <input type="name" class="form-control" id="name" placeholder="Enter name" name="name">
    </div>
    <div class="form-group">
      <label for="birthdate">Birth Date:</label>
      <input type="date" class="form-control" id="date" placeholder="Enter birthdate" name="birthdate">
    </div>
    <div class="form-group">
      <label for="username">Username:</label>
      <input type="username" class="form-control" id="username" placeholder="Enter username" name="nuserame">
    </div>
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pwd">
    </div>
    <div class="form-group">
      <label for="pwd-repeat">Repeat password:</label>
      <input type="password" class="form-control" id="pwd" placeholder="Repeat password" name="pwd-repeat">
    </div>
    <div class="checkbox">
      <label><input type="checkbox" name="remember">Remember me</label>
    </div>
    <button type="submit" class="btn btn-default" style="margin-bottom: 50px; background-color: #21BADC; font-family: 'Montserrat'">Submit</button>
  </form>
</div>

</body>
</html>

webapp/templates/home.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html>
<head>

<title>Bang</title>

<link href="{%static 'css/style.css'%}" rel="stylesheet" type="text/css">
  <style type=”text/css”> 
  </style> 
 
<!-- Font-->
<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Arvo' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Fira Sans' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet'>


<!-- CSS Header-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- CSS Header-->

<!-- CSS Profile-->

<!-- CSS Gallery footer-->
</head>
<header>
  {% include "partials/header.html" %}
</header>
<body>

<!-- Header 
<div class="header">
  <a href="/home">
    <img src="https://imgur.com/5mz2wC1.png" class="logo" href="bang2.html"></img></a>

    <div class="header-right">
      <a class="active" href="#home">Home</a>
      <a href="/skills/">Skills</a>
      <a href="/portfolio/">Portfolio</a>
      <a href="/tips/">Tips</a>
      <a href="/form/">Register</a>
    </div>
</div>
-->

<!--
<div style="padding-left:20px">
  <h1>Responsive Header</h1>
  <p>Resize the browser window to see the effect.</p>
  <p>Some content..</p>
</div>
-->

<!-- Profile -->

<h2 style="text-align: center;"><b>Profile</b></h2>

<div class="card">
  <img src="https://scontent.fcgk4-2.fna.fbcdn.net/v/t1.0-9/40987244_2051814751496829_6527488229854150656_n.jpg?_nc_cat=0&oh=6c47f2084bf646631293ab8ebb6aef70&oe=5C22D185" alt="abang" style="width:100%">
  <h1>Siti Aulia Rahmatussyifa</h1>
  <p class="npm">Jakarta, Indonesia</p>
  <desc style="font-size:80%;">I'm a student and passionate about travel. Enthusiast about sport, music, and photography.</desc>
  <div style="margin-top: 10px;"> 
    <a href="http://twitter.com/sarsyifa" target="_blank"><img src="https://marvel-live.freetls.fastly.net/canvas/2018/9/5d3d780bc5f54281a95161f21bc6f343?quality=95&fake=.png" alt="twitter" style="width:12%"></a>
    <a href="https://plus.google.com/u/0/106198580709783861549" target="_blank"><img src="https://marvel-live.freetls.fastly.net/canvas/2018/9/c3c9ce5e47514cbe82e7aa3aee4e6637?quality=95&fake=.png" alt="g+" style="width:12%"></a>   
    <a href="http://facebook.com/sar.syifa" target="_blank"><img src="https://marvel-live.freetls.fastly.net/canvas/2018/9/3ae1d17d4900438881f4eda63cd50553?quality=95&fake=.png" alt="fb" style="width:12%; transform: translate(5%);"></a</a>
    <a href="http://instagram.com/sarsyifa" target="_blank"><img src="https://marvel-live.freetls.fastly.net/canvas/2018/9/fb23d13f1beb45f8b2efb5df183e1029?quality=95&fake=.png" alt="ig+" style="width:10%"></a</a>  
  </div>

 <p><button><a href="mailto:sarsyifa@gmail.com" style="color: #47525E">Contact Me</a></button></p>
</div>


<!-- The four columns
<div class="row">
  <div class="column">
    <img src="https://scontent-sin6-2.xx.fbcdn.net/v/t1.0-9/41462103_2058283280849976_4046114477098139648_o.jpg?_nc_cat=0&oh=fe463e19efac5bd8d12bba84e5d0b2e2&oe=5BEF03C3" alt="Bandung" style="width:100%" onclick="openFoto(this);">
  </div>
  <div class="column">
    <img src="https://scontent-sin6-2.xx.fbcdn.net/v/t31.0-8/12247809_1067221403289507_6870572139527682517_o.jpg?_nc_cat=0&oh=8965c7690aa0684a10f75c8917fd56af&oe=5C1F763D" alt="Belitung" style="width:100%" onclick="openFoto(this);">
  </div>
  <div class="column">
    <img src="https://scontent-sin6-2.xx.fbcdn.net/v/t31.0-8/12646623_10204312370888396_5212380856309580000_o.jpg?_nc_cat=0&oh=f811f96c1da1d4347c9fab973249db00&oe=5C22BA08" alt="Madura" style="width:100%" onclick="openFoto(this);">
  </div>
  <div class="column">
    <img src="https://scontent-sin6-2.xx.fbcdn.net/v/t1.0-9/41363477_2058283454183292_7115979520561119232_o.jpg?_nc_cat=0&oh=a49fc9f900652043d87b27881217b2d6&oe=5C2B717B" alt="Bogor" style="width:100%" onclick="openFoto(this);">
  </div>
</div>

<div class="container">
  <span onclick="this.parentElement.style.display='none'" class="closebtn">&times;</span>
  <img id="expandedImg" style="width:100%">
  <div id="imgtext"></div>
</div>

<script>
function openFoto(imgs) {
    var expandImg = document.getElementById("expandedImg");
    var imgText = document.getElementById("imgtext");
    expandImg.src = imgs.src;
    imgText.innerHTML = imgs.alt;
    expandImg.parentElement.style.display = "block";
}
</script>
-->

</body>

</html>

webapp/templates/page5.html
{% load staticfiles %}
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>

	<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1" >

	<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
	<link href='https://fonts.googleapis.com/css?family=Arvo' rel='stylesheet'>
	<link href='https://fonts.googleapis.com/css?family=Fira Sans' rel='stylesheet'>
	<link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet'>

	<style >
		p {
			font-size: 15px;
			max-width: 400px;
		}

	</style>
</head>	

	<body class="container-fluid">

		<!-- reuse navbar -->
	 	<header>
	 		{% include "partials/header.html" %}
	 	</header>

	 	{% block content %}
		

		<div class = "container p-5">
			<h3 style="font-family: 'Montserrat'">Your schedule</h3>
			<div class="table-responsive">
				<table class="table">
					<thead>
						<th>Name</th>
						<th>Location</th>
						<th>Category</th>
						<th>Date</th>
						<th>Time</th>
					</thead>
					<tbody>
						{% for e in events %}
						<tr>
							<td>{{e.kegiatan}}</td>
							<td>{{e.location}}</td>
							<td>{{e.category}}</td>
							<td>{{e.tanggal|date:"l, j F Y"}}</td>
							<td>{{e.waktu|date:"H:i"}}</td>

							<!-- <td>{{e.date|date:"l, j F Y"}}</td>
							<td>{{e.time|date:"H:i"}}</td> -->
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>

		<div class = "container p-5">
			<h3 style="font-family: 'Montserrat'">Add new event</h3>
			<form method="POST">
				{% csrf_token %}
				{{ abang|crispy }}
				<br>
				<button type="submit" class="btn btn-primary">Add event</button>
			</form>
			<br>
			<form method="POST" action="{% url 'webapp:deleteall' %}">
			{% csrf_token %}
			<button type="submit" class="btn btn-primary">Delete all event</button>	
			</form>

		</div>


		

		{% endblock %}
	</body>



	</body>
</html>

webapp/templates/partials/header.html
{% load staticfiles %}
{% load static %}
<link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css">
<div class="header">
  <a href="{% url 'webapp:home' %}">
    <img src="https://imgur.com/5mz2wC1.png" class="logo" href=#></img></a>
     <!-- <meta name="viewport" content="width=device-width, initial-scale=1">-->

    <div class="header-right">
      <a href="{% url 'webapp:home' %}">Home</a>
      <a href="{% url 'webapp:skills' %}">Skills</a>
      <a href="{% url 'webapp:portfolio' %}">Portfolio</a>
      <a href="{% url 'webapp:tips' %}">Tips</a>
      <a href="{% url 'webapp:form' %}">Register</a>
      <a href="{% url 'webapp:activity' %}">Schedule</a>
    </div>
</div>

webapp/templates/portfolio.html
{% load staticfiles %}
{%load static%}
<!DOCTYPE html>
<html>
<head>
<link href="{%static 'css/style.css'%}" rel="stylesheet" type="text/css">
  <style type=”text/css”> 
  </style> 

<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
<title>Portfolio</title>
<!-- CSS Header-->
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<header>
  {% include "partials/header.html" %}
</header>

<body>

<div style="text-align:center">
  <h2 style="color: #47525; font-family:Montserrat;">Portfolio</h2>
  <p style="font-family: 'Montserrat'; color: #47525E; text-align: center;">Click on the images below:</p>
</div>

<!-- The four columns -->
<div class="row">
  <div class="column">
    <img src="https://scontent-sin6-2.xx.fbcdn.net/v/t1.0-9/41462103_2058283280849976_4046114477098139648_o.jpg?_nc_cat=0&oh=fe463e19efac5bd8d12bba84e5d0b2e2&oe=5BEF03C3" alt="Bandung" style="width:100%" onclick="openFoto(this);">
  </div>
  <div class="column">
    <img src="https://scontent-sin6-2.xx.fbcdn.net/v/t31.0-8/12247809_1067221403289507_6870572139527682517_o.jpg?_nc_cat=0&oh=8965c7690aa0684a10f75c8917fd56af&oe=5C1F763D" alt="Belitung" style="width:100%" onclick="openFoto(this);">
  </div>
  <div class="column">
    <img src="https://scontent-sin6-2.xx.fbcdn.net/v/t31.0-8/12646623_10204312370888396_5212380856309580000_o.jpg?_nc_cat=0&oh=f811f96c1da1d4347c9fab973249db00&oe=5C22BA08" alt="Madura" style="width:100%" onclick="openFoto(this);">
  </div>
  <div class="column">
    <img src="https://scontent-sin6-2.xx.fbcdn.net/v/t1.0-9/41363477_2058283454183292_7115979520561119232_o.jpg?_nc_cat=0&oh=a49fc9f900652043d87b27881217b2d6&oe=5C2B717B" alt="Bogor" style="width:100%" onclick="openFoto(this);">
  </div>
</div>

<div class="container">
  <span onclick="this.parentElement.style.display='none'" class="closebtn">&times;</span>
  <img id="expandedImg" style="width:100%">
  <div id="imgtext"></div>
</div>

<script>
function openFoto(imgs) {
    var expandImg = document.getElementById("expandedImg");
    var imgText = document.getElementById("imgtext");
    expandImg.src = imgs.src;
    imgText.innerHTML = imgs.alt;
    expandImg.parentElement.style.display = "block";
}
</script>

</body>
</html>